# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "grotesk-iconesque-cv"
version = "1.0.2"
entrypoint = "src/lib.typ"
authors = ["Bailey Bjornstad <https://github.com/bbjornstad>"]
license = "Unlicense"
description = "A clean CV and cover letter template based on Brilliant-cv and fireside templates."
repository = "https://github.com/bbjornstad/grotesk-iconesque-cv"
keywords = ["cv", "resume", "cover-letter", "curriculum-vitae"]
categories = ["cv", "layout"]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "*.pdf",
  "cover_letter_example.png",
  "cv_example.png",
]

[template]
path = "src/template"
entrypoint = "cv.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
